module.exports = (User, Event) => Promise.all([
  // all user passwords are 'password'
  User.create({
    email: 's3bansal@ucsd.edu',
    accessType: 'STANDARD',
    state: 'ACTIVE',
    firstName: 'Sumeet',
    lastName: 'Bansal',
    hash: '$2b$10$WNZRaGHvj3blWAtosHrSDeH4wuSkpwmEVq4obpKr4nujs4XavIgmG',
    points: 125,
    graduationYear: 2020,
    major: 'Computer Science',
  }),

  User.create({
    email: 'jrpadua@ucsd.edu',
    accessType: 'STAFF',
    state: 'ACTIVE',
    firstName: 'Jaden',
    lastName: 'Padua',
    hash: '$2b$10$WNZRaGHvj3blWAtosHrSDeH4wuSkpwmEVq4obpKr4nujs4XavIgmG',
    points: 205,
    graduationYear: 2022,
    major: 'Computer Science',
  }),

  User.create({
    email: 'stao@ucsd.edu',
    accessType: 'RESTRICTED',
    state: 'ACTIVE',
    firstName: 'Stone',
    lastName: 'Tao',
    hash: '$2b$10$WNZRaGHvj3blWAtosHrSDeH4wuSkpwmEVq4obpKr4nujs4XavIgmG',
    points: 195,
    graduationYear: 2021,
    major: 'Computer Science',
  }),

  User.create({
    email: 'jpan@ucsd.edu',
    accessType: 'STANDARD',
    state: 'ACTIVE',
    firstName: 'Paul',
    lastName: 'Pan',
    hash: '$2b$10$WNZRaGHvj3blWAtosHrSDeH4wuSkpwmEVq4obpKr4nujs4XavIgmG',
    graduationYear: 2020,
    major: 'Mathematics - Computer Science',
  }),

  User.create({
    email: 'stl005@ucsd.edu',
    accessType: 'STAFF',
    state: 'ACTIVE',
    firstName: 'Stanley',
    lastName: 'Lee',
    hash: '$2b$10$WNZRaGHvj3blWAtosHrSDeH4wuSkpwmEVq4obpKr4nujs4XavIgmG',
    points: 55,
    graduationYear: 2020,
    major: 'Data Science',
  }),

  User.create({
    email: 'kenakai@ucsd.edu',
    accessType: 'STANDARD',
    state: 'ACTIVE',
    firstName: 'Kendall',
    lastName: 'Nakai',
    hash: '$2b$10$WNZRaGHvj3blWAtosHrSDeH4wuSkpwmEVq4obpKr4nujs4XavIgmG',
    points: 160,
    graduationYear: 2020,
    major: 'Computer Engineering',
  }),

  Event.create({
    title: 'Bit-Byte Allocation',
    description: 'The big reveal is here!',
    committee: '',
    location: 'Qualcomm Room',
    start: new Date(Date.now() - 86400000),
    end: new Date(Date.now() - 82800000),
    attendanceCode: 'malloc',
    pointValue: 20,
  }),

  Event.create({
    title: 'Hack School - NodeJS',
    description: 'Learn Node.',
    committee: '',
    location: 'PC ERC Room',
    start: new Date(Date.now() - 3600000),
    end: new Date(Date.now() + 3600000),
    attendanceCode: 'n0d3',
    pointValue: 30,
    requiresStaff: true,
    staffPointBonus: 5,
  }),

  Event.create({
    title: 'ACM Eats: Taco Stand',
    description: 'Taco Tuesday.',
    committee: '',
    location: 'PC Loop',
    start: new Date(Date.now() - 3600000),
    end: new Date(Date.now() + 3600000),
    attendanceCode: 'tac0',
    pointValue: 15,
  }),

  Event.create({
    title: 'Pool and Ping Pong',
    description: 'Game night.',
    committee: '',
    location: 'PC Game Room',
    start: new Date(Date.now() + 82800000),
    end: new Date(Date.now() + 86400000),
    attendanceCode: 'p0ng',
    pointValue: 10,
  }),
]);
