extends:
  - "eslint:recommended"
  - "airbnb-typescript/base"
parserOptions:
  project: './tsconfig.json'
env:
  browser: true
  node: true
  jest: true
rules:
  "@typescript-eslint/no-unused-vars":
    - "error"
    - argsIgnorePattern: "type"
  class-methods-use-this:
    - "warn"
    - exceptMethods:
      - "up"
      - "down"
      - "validate"
      - "defaultMessage"
  consistent-return: off
  func-names: "off"
  global-require: "off"
  import/no-cycle: "off"
  import/prefer-default-export: "off"
  max-classes-per-file: "off"
  max-len:
    - "error"
    - code: 120
  no-bitwise:
    - "error"
    - allow:
        - "^"
  no-param-reassign: "off"
  no-unused-vars: "off"
  object-curly-newline:
    - "error"
    - consistent: true
