extends:
  - "eslint:recommended"
  - "airbnb-typescript/base"
parserOptions:
  project: './tsconfig.json'
env:
  browser: true
  node: true
  jest: true
rules:
  "@typescript-eslint/no-misused-promises":
    - "error"
  "@typescript-eslint/no-unused-vars":
    - "error"
    - argsIgnorePattern: "type|_*"
  class-methods-use-this: "off"
  consistent-return: off
  func-names: "off"
  global-require: "off"
  import/no-cycle: "off"
  import/prefer-default-export: "off"
  max-classes-per-file: "off"
  max-len:
    - "error"
    - code: 120
  no-bitwise:
    - "error"
    - allow:
        - "^"
  no-param-reassign: "off"
  no-unused-vars: "off"
  object-curly-newline:
    - "error"
    - consistent: true
overrides:
- files:
    - "tests/*.test.ts"
  rules:
    no-await-in-loop: "off"

