extends:
  - "eslint:recommended"
  - "airbnb-base"
env:
  browser: true
  node: true
rules:
  global-require: "off"
  max-classes-per-file: "warn"
  max-len:
    - "error"
    - code: 120
  no-unused-vars:
    - "error"
    - argsIgnorePattern: "next"
overrides:
  -
    files:
      - "./app/error/index.js"
    rules:
      no-param-reassign: "off"
