const TABLE_NAME = 'Users';
module.exports = {
  // all user passwords are 'password'
  up: (queryInterface, Sequelize) => queryInterface.bulkInsert(TABLE_NAME, [{
    uuid: '2bf4c870-80d3-4fe8-885c-85cc1925faf9',
    email: 's3bansal@ucsd.edu',
    accessType: 'STANDARD',
    state: 'ACTIVE',
    firstName: 'Sumeet',
    lastName: 'Bansal',
    hash: '$2b$10$WNZRaGHvj3blWAtosHrSDeH4wuSkpwmEVq4obpKr4nujs4XavIgmG',
    points: 125,
    graduationYear: 2020,
    major: 'Computer Science',
  }, {
    uuid: 'e0880a3b-f845-4f15-a9f9-c3315ccb0d77',
    email: 'stl005@ucsd.edu',
    accessType: 'STAFF',
    state: 'ACTIVE',
    firstName: 'Stanley',
    lastName: 'Lee',
    hash: '$2b$10$WNZRaGHvj3blWAtosHrSDeH4wuSkpwmEVq4obpKr4nujs4XavIgmG',
    points: 55,
    graduationYear: 2022,
    major: 'Data Science',
  }, {
    uuid: 'bb063686-9579-4020-81fa-3c27b3c45b4c',
    email: 'stao@ucsd.edu',
    accessType: 'STANDARD',
    state: 'PENDING',
    firstName: 'Stone',
    lastName: 'Tao',
    hash: '$2b$10$WNZRaGHvj3blWAtosHrSDeH4wuSkpwmEVq4obpKr4nujs4XavIgmG',
    points: 195,
    graduationYear: 2021,
    major: 'Computer Science',
  }, {
    uuid: '72a16fb4-c3c8-4b22-b5a9-971589e1c624',
    email: 'jpan@ucsd.edu',
    accessType: 'STANDARD',
    state: 'ACTIVE',
    firstName: 'Paul',
    lastName: 'Pan',
    hash: '$2b$10$WNZRaGHvj3blWAtosHrSDeH4wuSkpwmEVq4obpKr4nujs4XavIgmG',
    graduationYear: 2020,
    major: 'Mathematics - Computer Science',
  }, {
    uuid: '4bdab5fa-23e9-4a30-be0f-518a5c56009e',
    email: 'asudhart@ucsd.edu',
    accessType: 'STANDARD',
    state: 'ACTIVE',
    firstName: 'Kendall',
    lastName: 'Nakai',
    hash: '$2b$10$WNZRaGHvj3blWAtosHrSDeH4wuSkpwmEVq4obpKr4nujs4XavIgmG',
    points: 160,
    graduationYear: 2022,
    major: 'Computer Engineering',
  }, {
    uuid: '7dc03709-4a52-4ff1-b886-982a56d3d0de',
    email: 'smhariha@ucsd.edu',
    accessType: 'STANDARD',
    state: 'ACTIVE',
    firstName: 'Shravan',
    lastName: 'Hariharan',
    hash: '$2b$10$WNZRaGHvj3blWAtosHrSDeH4wuSkpwmEVq4obpKr4nujs4XavIgmG',
    points: 750,
    graduationYear: 2023,
    major: 'Computer Science',
  }]),

  down: (queryInterface, Sequelize) => queryInterface.bulkDelete(TABLE_NAME, null, {}),
};
