name: Auto Comment on PRs
on: pull_request
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/auto-comment@v1.0.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: >
            Thanks for contributing! Please make sure to bump the package version&mdash;
            see [this guide to semantic versioning](https://semver.org/))&mdash; and
            document API changes as appropriate.
